filebeat.inputs:
  - type: filestream
    id: go-json-logs
    paths:
      - /app-logs/app.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

logging.level: debug
